name: CMake


on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 Tests:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3

  - name: Adding googletest
    run: git clone https://github.com/google/googletest.git third-party/googletest -b release-1.11.0

  - name: Install lcov
    run: sudo apt-get install -y lcov

  - name: Config Stratergy with tests
    run: cmake -H. -B ${{github.workspace}}/build -DBUILD_TESTS=ON

  - name: Build Stratergy
    run: cmake --build ${{github.workspace}}/build

  - name: Run tests
    run: build/check
    
  - name: Do lcov stuff
    run: lcov -c -d build/CMakeFiles/Stratergy.dir/Stratergy/ --include *.cpp --output-file ./coverage/lcov.info    
