name: CMake


on:
 push:
  branches: [master]
 pull_request:
  branches: [master]

jobs:
 Tests:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v3

   - name: Set up CMake
      uses: lukka/get-cmake@v3

  - name: Adding googletest
    run: git clone https://github.com/google/googletest.git third-party/googletest -b release-1.11.0

 - name: Install dependencies
      run: sudo apt-get install -y ninja-build

       - name: Configure CMake
      run: cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=Release -G Ninja


  - name: Config Stratergy with tests
    run: cmake -H. -B ${{github.workspace}}/build -DBUILD_TESTS=ON

  - name: Build Stratergy
    run: cmake --build ${{github.workspace}}/build

  - name: Run tests
    run: build/check
    
  - name: Upload executable as artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-executable
        path: ${{github.workspace}}/build/my-executable

         - name: Run tests
      run: ctest --output-on-failure -C Release -VV --test-dir build
